/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev` / `npx convex deploy`.
 * See the note in `dataModel.d.ts` about this checked-in copy. `anyApi` builds
 * function references purely from the property-access path, so this runtime
 * fallback is correct regardless of the exact module map above.
 *
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
