/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev` / `npx convex deploy`.
 * See the note in `dataModel.d.ts` about this checked-in copy.
 *
 * @module
 */

import type * as auth from "../auth.js";
import type * as authConfig from "../auth.config.js";
import type * as careerProfile from "../careerProfile.js";
import type * as http from "../http.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  "auth.config": typeof authConfig;
  careerProfile: typeof careerProfile;
  http: typeof http;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
