/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev` / `npx convex deploy`.
 * This checked-in copy was hand-authored against the installed `convex` package's
 * type exports (network access to push a real deploy and regenerate this file
 * wasn't available when this project was scaffolded); the next real deploy will
 * overwrite it with the canonical output.
 *
 * @module
 */

import type {
  DataModelFromSchemaDefinition,
  DocumentByName,
  TableNamesInDataModel,
  SystemTableNames,
} from "convex/server";
import type { GenericId } from "convex/values";
import schema from "../schema.js";

/**
 * The names of all of your Convex tables.
 */
export type TableNames = TableNamesInDataModel<DataModel>;

/**
 * The type of a document stored in Convex.
 */
export type Doc<TableName extends TableNames> = DocumentByName<
  DataModel,
  TableName
>;

/**
 * An identifier for a document in Convex.
 */
export type Id<TableName extends TableNames | SystemTableNames> =
  GenericId<TableName>;

/**
 * A type describing your Convex data model.
 */
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
