/**
 * Generated `query`/`mutation`/`action` helpers.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev` / `npx convex deploy`.
 * See the note in `dataModel.d.ts` about this checked-in copy.
 *
 * @module
 */

import {
  actionGeneric,
  httpActionGeneric,
  mutationGeneric,
  queryGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";

export const query = queryGeneric;
export const internalQuery = internalQueryGeneric;
export const mutation = mutationGeneric;
export const internalMutation = internalMutationGeneric;
export const action = actionGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;
